# Generated by Django 2.2.14 on 2020-10-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('verifiedUser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientMail', models.EmailField(max_length=254)),
                ('createdDate', models.DateTimeField()),
                ('messageDetail', models.CharField(max_length=100)),
                ('triggerDateTime', models.DateTimeField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventReminder.User')),
            ],
        ),
    ]
