# Generated by Django 2.2.14 on 2020-10-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventReminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='EventProgress',
            field=models.CharField(default='p', max_length=1),
            preserve_default=False,
        ),
    ]
