# Generated by Django 2.2.14 on 2020-10-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventReminder', '0002_eventreminder_eventprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventreminder',
            options={'ordering': ['-triggerDateTime']},
        ),
    ]
